### ISSUE TITLE
Returns 200 when custom check raises Exception

### ISSUE THREAD

**Issue by kiarashazarnia** [mwarkentin/django-watchman#188] opened 2022-11-24 14:56 UTC
**Describe the bug**

Returns 200 when custom check raises Exception on the health service.

**To Reproduce**

implement a custom check like this:

```python
# in settings file

from watchman import constants as watchman_constants

WATCHMAN_CHECKS = watchman_constants.DEFAULT_CHECKS + (
    "utils.custom_health_checks.db_write_health_check",
)
WATCHMAN_DATABASES = ["default"]

WATCHMAN_ERROR_CODE = 500


# in the utils file
@check
def db_write_health_check():
    raise Exception()
```

**Expected behavior**

I expect a non-OK overall response but it gets something like this:

```
{"storage": {"ok": true}, "ok": false, "error": "", "stacktrace": "Traceback (most recent call last):\n  File \"/home/kiarash/Documents/work/code/iam/bepa2/venv/lib/python3.8/site-packages/watchman/decorators.py\", line 29, in wrapped\n    response = func(*args, **kwargs)\n  File \"/home/kiarash/Documents/work/code/iam/bepa2/src/utils/custom_health_checks.py\", line 19, in db_write_health_check\n    raise Exception()\nException\n", "databases": [{"default": {"ok": true}}], "caches": [{"default": {"ok": true}}]}
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python version: 3.8
 - Django-watchman version 1.3.0
 - Django-watchman settings
 - Custom checks

Explained in the Code Sample.

**Comment by mwarkentin** [comment] 2022-11-25 04:13
@kiarashazarnia thanks for opening this issue - sorry this isn't working as you'd expected!

Can you confirm for me the response code on the request? Eg. if you're using `curl` to call the endpoint could you run `curl -I` and paste the output?

The expected behaviour with your config would be to return the response you provided, but it would be a `500` error code (see `WATCHMAN_ERROR_CODE = 500`) instead of a `200` (OK) response if all checks were successful. You can find the logic for that here:

* https://github.com/mwarkentin/django-watchman/blob/main/watchman/views.py#L73-L83
* https://github.com/mwarkentin/django-watchman/blob/main/watchman/views.py#L103-L104

This will allow a monitoring tool like pingdom to be used and send an alert if it starts receiving error codes back from the endpoint. If that's not the behaviour you're seeing (eg. you get a `200` back) then that would be a bug that will need to be fixed!

If you want to determine whether all checks are ok or not based on the body of the response instead of the status code, you would need to parse the response and iterate through the checks to confirm.

**Comment by kiarashazarnia** [comment] 2022-11-25 06:07
Thanks for your informative response dear @mwarkentin.
I hope this will help:

```bash
$ curl -I http://localhost:8000/api/v1/healthz

HTTP/1.1 200 OK
Date: Fri, 25 Nov 2022 05:48:53 GMT
Server: WSGIServer/0.2 CPython/3.8.10
Content-Type: application/json
X-Frame-Options: DENY
Content-Length: 591
Vary: Accept-Language
Content-Language: en
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin


$ curl -i http://localhost:8000/api/v1/healthz
HTTP/1.1 200 OK
Date: Fri, 25 Nov 2022 06:03:57 GMT
Server: WSGIServer/0.2 CPython/3.8.10
Content-Type: application/json
X-Frame-Options: DENY
Content-Length: 591
Vary: Accept-Language
Content-Language: en
X-Content-Type-Options: nosniff
Referrer-Policy: same-origin

{"caches": [{"default": {"ok": tru$ e}}], "ok": false, "error": "Thanks dear mwarkentin!", "stacktrace": "Traceback (most recent call last):\n  File \"/home/kiarash/Documents/work/code/iam/bepa2/venv/lib/python3.8/site-packages/watchman/decorators.py\", line 29, in wrapped\n    response = func(*args, **kwargs)\n  File \"/home/kiarash/Documents/work/code/iam/bepa2/src/utils/custom_health_checks.py\", line 18, in db_write_health_check\n    raise Exception(\"Thanks dear mwarkentin!\")\nException: Thanks dear mwarkentin!\n", "databases": [{"default": {"ok": true}}], "storage": {"ok": true}}
```

With this custom health check function:

```python
@check
def db_write_health_check():
    raise Exception("Thanks dear mwarkentin!")
```

**Comment by mwarkentin** [comment] 2022-11-25 13:44
Thanks, that doesn't seem right. I'll need to try to reproduce myself to figure out what's going on.

**Comment by mwarkentin** [comment] 2022-11-25 13:49
@kiarashazarnia could you also visit `/watchman/dashboard` and paste a screenshot of what you see?

**Comment by mwarkentin** [comment] 2022-11-25 13:56
I've reproduced the issue here: https://github.com/mwarkentin/django-watchman/pull/189

I'll let you know when I have a fix available.. thanks!

**Comment by mwarkentin** [comment] 2022-11-25 14:48
@kiarashazarnia Ok, it looks like the docs are not correct, and the current way you need to use the `@check` decorator is from within a wrapper. If you take a look at the [builtin checks](https://github.com/mwarkentin/django-watchman/blob/main/watchman/checks.py#L76-L89) this is how they work as well.

```
from watchman.decorators import check


def custom_check():
    return {"custom_check": _custom_check()}

@check
def _custom_check():
    raise Exception("The answer is 42")
    return {"ok": True}
```

When implemented like this, here is what I get when I raise an exception in my custom check:

```
❯ http http://0.0.0.0:8000/watchman/
HTTP/1.1 500 Internal Server Error
Content-Length: 541
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Fri, 25 Nov 2022 14:44:23 GMT
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.11.0
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Watchman-Version: 1.3.0

{
    "caches": [
        {
            "default": {
                "ok": true
            }
        }
    ],
    "custom_check": {
        "error": "The answer is 42",
        "ok": false,
        "stacktrace": "Traceback (most recent call last):\n  File \"/app/watchman/decorators.py\", line 29, in wrapped\n    response = func(*args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"/app/sample_project/sample_project/checks.py\", line 9, in _custom_check\n    raise Exception(\"The answer is 42\")\nException: The answer is 42\n"
    },
    "databases": [
        {
            "default": {
                "ok": true
            }
        },
        {
            "secondary": {
                "ok": true
            }
        }
    ],
    "storage": {
        "ok": true
    }
}
```

Dashboard:

![image](https://user-images.githubusercontent.com/67560/204008829-7051d954-4916-4f76-9e5a-590eb818d47a.png)


And if it returns `{"ok: True}`:

```
❯ http http://0.0.0.0:8000/watchman/
HTTP/1.1 200 OK
Content-Length: 165
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Fri, 25 Nov 2022 14:45:55 GMT
Referrer-Policy: same-origin
Server: WSGIServer/0.2 CPython/3.11.0
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Watchman-Version: 1.3.0

{
    "caches": [
        {
            "default": {
                "ok": true
            }
        }
    ],
    "custom_check": {
        "ok": true
    },
    "databases": [
        {
            "default": {
                "ok": true
            }
        },
        {
            "secondary": {
                "ok": true
            }
        }
    ],
    "storage": {
        "ok": true
    }
}
```

Dashboard:

![image](https://user-images.githubusercontent.com/67560/204008538-b930438c-7077-4839-ad21-41940da9b145.png)

**Comment by mwarkentin** [comment] 2022-11-25 15:19
I've updated the sample project with 2 custom checks (one successful, one failing), I'll open a separate PR to update the docs on writing custom checks.

I suspect it's possible to make the `@check` operator smarter and not need to be wrapped, but I don't have time to look into that currently. If it's something you'd be interested in working on, let me know.

**Comment by kiarashazarnia** [comment] 2022-11-25 15:28
Thanks for your attention, yeah... I'm willing to have some contribution and honestly, I have an idea to fix it.
I will inform you as soon as I find time to share my idea with you in a PR. I will be happy to be notified if you fix it sooner or have some advice or a contribution guide link for me.
Good Luck

**Comment by mwarkentin** [comment] 2022-11-25 15:56
@kiarashazarnia I'm going to close this off with the doc and example update, I've created a separate issue which describes the decorator improvement if you'd like to take a crack at it sometime: #191

**Closed** 2022-11-25 15:59 UTC
Labels: bug
